collection:
  managers:
    - type: rent
      processors:
        - id: skelbiu
          stores:
          - type: turso
            endpoint: libsql://psec-db-dev-dovydasdo.turso.io
          data_sources:
          - name: rent_ads 
            stream: rent_ads
            subject: rent_ad.skelbiu.>
            type: rent_ads
            dump: daily
            source_type: nats
          # - name: location_cache
          #   stream: locations 
          #   subject: none
          #   type: locations
          #   dump: none 
          #   source_type: nats_cache
