collection:
  data_sources:
    - name: skelbiu_ads
      stream: rent_ad.skelbiu.>
      kv_name: locations
      store: turso
      type: rent
      dump: daily
    # - name: aruodas_ads
    #   stream: rent_ad.aruodas.>
    #   kv_name: locations
    #   store: turso
    #   type: rent
    #   dump: daily
