apiVersion: v1
kind: Service
metadata:
  name: nats-service
  namespace: default
spec:
  type: LoadBalancer  # or NodePort
  ports:
    - port: 4222
      targetPort: 4222
  selector:
    app: nats-0
